### PR TITLE
Support for other response types then code & token

### LINKED ISSUE #626: Support for other response types then code & token.
The current codebase already provides many hooks for customizing the behaviour like enhancing tokens, allow custom grant types, pre-approval of authorization requests and so on. What it currently does not support is hooking in custom behaviour for handling other response-types then code & token in the Authorization endpoint. 

The oauth 2.0 authorization framework specification has a [section](https://tools.ietf.org/html/rfc6749#section-8.4) about new authorization endpoint response types. 

Allowing for custom response types handlers would enable users of the framework to easily implement features like the id_token & none response types defined in the [openid oauth2 specification](http://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#id_token) without having to change the actual spring oauth2 framework.

All the needed hooks are already there in the AuthorizationEndpoint and a minimalistic implementation would mean introducing a CustomResponseTypesHandler that is capable of handling custom response types other then code & token.

I would like to write a pull request for this, but before putting in the effort I was wondering if this is something the core committers would consider viable?

### PR DESCRIPTION
**Pull request by oharsta**
Allow for injection of CustomResponseTypesHandler in the
AuthorizationEndpoint to support for other response types other then
the default 'code' and 'token'.

The CustomResponseTypesHandler can be configured using
AuthorizationServerEndpointsConfigurer#customResponseTypesHandler or
using xml style with a custom-response-types-handler-ref on the
oauth2:authorization-code.

Resolves #626

### CODE REVIEW

**Comment by oharsta** [comment]
The https://travis-ci.org/spring-projects/spring-security-oauth/builds/91321307 build fails, but it seems totally unrelated to my code. Also locally when running mvn clean test -P bootstrap everything is green. False negative?

**Comment by pivotal-issuemaster** [comment]
@oharsta Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=627) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by oharsta** [comment]
@pivotal-issuemaster , I already signed the Contributor License Agreement some time ago. See https://github.com/spring-projects/spring-security-oauth/pull/50. My confirmation number is 33620120911014936.

**Comment by danielwegener** [comment]
👍  !

**Comment by pivotal-issuemaster** [comment]
@oharsta Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=627)!

**Comment by rwinch** [comment]
Closing as this is stale and needs rebased. If this is still valid, please rebase and submit an additional PR

**Pull request closed without merging**
