### PR TITLE
Alter AuthorizationEndpoint so that it handles urn:ietf:wg:oauth:2.0:…

### PR DESCRIPTION
**Pull request by jnawk**
…oob and urn:ietf:wg:oauth:2.0:oob:auto redirect URLs the same way Google does

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jnawk Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=802) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jnawk Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=802)!

**Comment by jgrandja** [comment]
@jnawk Can you please provide more details on this proposed update? I don't understand the need for it?

**Comment by jnawk** [comment]
Take it or leave it.  You left it 4 years and until the project has been consigned to the dustbin before even looking at this, so I see no reason to invest any further.

**Pull request closed without merging**
