### PR TITLE
Alter AuthorizationServerSecurityConfigurer to allow custom authentication filters for the TokenEndpoint.

### PR DESCRIPTION
**Pull request by michaeltecourt**
Alter `AuthorizationServerSecurityConfigurer` to allow custom authentication filters for the `TokenEndpoint`.

These filters are added upstream of the traditional `BasicAuthenticationFilter`.

Simple integration test project added, details in README.md.

### CODE REVIEW

**Comment by dsyer** [comment]
Thanks. Did you fill out the contributor's agreement (link in README)?

**Comment by michaeltecourt** [comment]
Yes sir !

**Comment by dsyer** [comment]
OK, great. Would you mind changing the method name from `addTokenEndpointCustomAuthenticationFilter` to simply `addTokenEndpointAuthenticationFilter`?

**Comment by michaeltecourt** [comment]
Ok I'll do that. 
BTW, I sent a handful of pull requests, two of them are not associated with issues (#598 and #599), I can create some if necessary.

**Comment by michaeltecourt** [comment]
Done :heavy_check_mark:

**Pull request closed without merging**
