### PR TITLE
Make WebResponseExceptionTranslator generic to ease custom error formats for resource servers

### PR DESCRIPTION
**Pull request by michaeltecourt**
The OAuth 2.0 specification defines how the authorization server error responses must be, but it does not force resource servers to adopt the same format. 
While adding OAuth 2.0 security to our services, we found it confusing for our clients to have to deal with two different error formats : one for "business errors" the other for authorization errors.

Making `WebResponseExceptionTranslator<T>` generic allows Resource Servers to easily implement their own error format on top of framework classes, instead of having to copy a bunch of classes : 
`AbstractOauth2SecurityExceptionHandler`, etc.

On the Authorization Server side, the only change is that components
explicitely define that the error type should be OAuth2Exception :
`WebResponseExceptionTranslator<OAuth2Exception>`

### CODE REVIEW

**Comment by michaeltecourt** [comment]
BTW the change is backward compatible. Only people who have already overriden related classes will get "generic type" warnings.

**Comment by pivotal-issuemaster** [comment]
@michaeltecourt Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=598) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@michaeltecourt Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=598)!

**Comment by maxkramerbcgdv** [comment]
LGTM!

**Comment by michaeltecourt** [comment]
Hi @jgrandja, I've rebased this PR against the master, the build is back to green.

Is there anything I can do to help this feature get merged ? a bunch of people have asked about it in issue #605.   
We have been using this code in production for the past two years, and I'd love to remove the duplicated classes in our codebase :)

**Comment by jgrandja** [comment]
@michaeltecourt I'll take a look at this when I return from the holiday break Jan 8.

**Comment by jgrandja** [comment]
@michaeltecourt I finally got around to this. Please see [comment](https://github.com/spring-projects/spring-security-oauth/issues/605#issuecomment-361460653)

**Comment by jgrandja** [comment]
Thanks for the PR @michaeltecourt ! This is now in master.

**Pull request closed without merging**
