### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by dangerdan**
Fixed typo on exception.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dangerdan Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=827) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by DeCaMil** [comment]
@dangerdan This pull is still open pending a signed Contributor License Agreement.
If you don't want to sign, let me know and I''l submit it.

**Comment by pivotal-issuemaster** [comment]
@dangerdan Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=827)!

**Comment by DeCaMil** [comment]
@dangerdan apparently this was just a case of synchronization.
All checks pass now.

**Comment by jgrandja** [comment]
Thanks for the PR @dangerdan. This is now in master.

**Pull request closed without merging**
