### PR TITLE
Add encoding for the jwt key value in the case of HMac signing

### PR DESCRIPTION
**Pull request by cdelmas**
Some authorization servers provide a secret which is encoded: auth0 for instance gives a base 64 encoded-url secret. This cannot be handled by Spring Security OAuth at this time (see http://stackoverflow.com/q/37832961/5903220).

This patch adds the possibility to configure an encoding for the key (at this time: base64 or base64url), and uses the MacSigner(byte[]) constructor to avoid data loss when converting back to String.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@cdelmas Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=794) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@cdelmas Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=794)!

**Comment by jjparsons** [comment]
@cdelmas I'm using Auth0 as well with HMAC. Is there anything else that you did special for Auth0? I'm adding roles to users in Auth0 as well via an Auth0 rule...

Given how popular Auth0 is it's unfortunate a workaround like this is required out of box. Are you still using your custom `JwtAccessTokenConverter`?

**Comment by cdelmas** [comment]
From the 6th of december, this won't be mandatory anymore as they decided to remove the encoding for new keys. A decent workaround is to use RSA.

**Comment by jjparsons** [comment]
Okay cool. I suppose that's easier yes because it only requires Auth0 config stuff. Thanks for the timely response.

**Comment by jgrandja** [comment]
@cdelmas If you're still looking to get this merged, please add a test and I can review.

**Comment by jgrandja** [comment]
@cdelmas I'm closing this PR due to lack of feedback from review.

If you still feel this is an issue, please submit a new PR and address the review feedback.

**Pull request closed without merging**
