### PR TITLE
Save token after successful authentication when an ClientTokenServices is provided.

### PR DESCRIPTION
**Pull request by KeesKoffeman**
Fixes gh-498

In addition to this it would be nice if ClientTokenServices is injected by auto-configuration (even when null) to avoid customization of both the filter and the rest template.

### CODE REVIEW

**Comment by dsyer** [comment]
Thanks. Did you fill out the contributor's agreement (link in README)?

**Comment by KeesKoffeman** [comment]
I did right after I filed the pull request. I selected 'spring-security' and named you as project lead; is that correct?

**Comment by dsyer** [comment]
That's fine. It's an automated system but I don't always get the notifications.

**Comment by Artgit** [comment]
When this feature will be available ? Also, is it safe to store token based only on authentication.getName(), resource.getClientId() and resource.getScope as implemented in DefaultClientKeyGenerator.extractKey method ?

I think there is a very good chance to face a collisions between OAuth2 providers in oauth_client_token table.

What do you think ?

**Comment by dsyer** [comment]
I think you have some very unusual providers if they have identical client id and scope names.

**Comment by Artgit** [comment]
For example in my current implementation authentication.getName() returns null. This way I think I'll have the only one record (authentication_id will be based for many users only on the same client_id and same scopes) in  oauth_client_token table

**Comment by dsyer** [comment]
Your `Authentication` is broken then, I guess. If you need to support null names then you should provide your own `ClientKeyGenerator`.

**Comment by Artgit** [comment]
Yeah.. I see it now.. According to UserDetails.getUsername() method contract it can't return null.. Right now struggling with a following question http://stackoverflow.com/questions/34920743/spring-security-userdetails-and-username

**Comment by pivotal-issuemaster** [comment]
@KeesKoffeman Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=499) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by kvandake** [comment]
Hello. What status it pull request? When will these changes committed?

**Comment by pivotal-issuemaster** [comment]
@KeesKoffeman Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=499)!

**Comment by bvulaj** [comment]
I've resyncd the PR and it looks like besides the conflict that this should be all set. Any chance of a merge soon?

**Comment by jgrandja** [comment]
@bvulaj With the addition of `setClientTokenServices(ClientTokenServices)` on the `Filter`, this could only get into the next minor release which would be 2.4. We haven't scheduled 2.4 as of yet and it likely won't be released for a couple months at least.

**Comment by jgrandja** [comment]
@KeesKoffeman As you may be aware, this project is scheduled to reach EOL. Please see the [announcement](https://spring.io/blog/2020/05/07/end-of-life-for-spring-security-oauth) for further details.

I'm going to close this PR as it doesn't make sense to merge these changes given the status of the project.

**Pull request closed without merging**
