### PR TITLE
Restricted token endpoint to HTTP POST by default.

### PR DESCRIPTION
**Pull request by ccampo133**
Restricted the token endpoint to only allow HTTP POST requests by default. Proposed solution to https://github.com/spring-projects/spring-security-oauth/issues/327

### CODE REVIEW

**Comment by dsyer** [comment]
Thanks. Did you fill out the contributor's agreement (link in README)?

**Comment by ccampo133** [comment]
Yessir :)

**Comment by vkhoroshko** [comment]
Could someone tell us how to override allowed methods if we're using <oauth:authorization-server in XML and not @EnableAuthorizationServer?

Thanks in advance

**Comment by dsyer** [comment]
What is your use case for requiring anything but a POST? I'm mainly interested because I think we should only allow POST.

**Comment by dsyer** [comment]
@vkhoroshko you can probably quite easily inject the `TokenEndpoint` into one of your beans and set the `allowedRequestMethods`.

**Comment by vkhoroshko** [comment]
The issue is that our clients are already using **GET** and we just can't break them.

For now we created post processor that sets `allowedRequestMethods`.

But, anyway, I believe this pull request is a little bit incomplete in terms that if something is allowed to be configured using class based configuration - the same should be allowed for XML configuration also.

**Comment by ccampo133** [comment]
Considering the OAuth 2 spec says that clients are **only** allowed to use POST, I think it is reasonable for an OAuth 2 library to match the spec. That being said, it is true that you can do this in Java config and not XML, but that can be said of quite a few things in Spring. Since there is a workaround, if this is even considered an issue, it should be a low priority.

**Comment by michael-simons** [comment]
In case anyone comes looking for this:

```
import java.util.HashSet;
import java.util.Set;

import org.springframework.beans.BeansException;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.http.HttpMethod;
import org.springframework.security.oauth2.provider.endpoint.TokenEndpoint;

public class TokenEndpointPostProcessor implements BeanPostProcessor {

	@Override
	public Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {
		if (bean instanceof TokenEndpoint) {
			final TokenEndpoint tokenEndpoint = (TokenEndpoint) bean;
			final Set<HttpMethod> allowedRequestMethods = new HashSet<>();
			allowedRequestMethods.add(HttpMethod.POST);
			allowedRequestMethods.add(HttpMethod.GET);
			tokenEndpoint.setAllowedRequestMethods(allowedRequestMethods);
		}
		return bean;
	}

	@Override
	public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
		return bean;
	}
}
```

@dsyer If i find the time to add this to the xml parser, any chance of merging it?

**Comment by pivotal-issuemaster** [comment]
@ccampo133 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=334)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=334) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ccampo133 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=334)!

**Pull request closed without merging**
