### PR TITLE
2.2.x

### PR DESCRIPTION
**Pull request by bhami**
spring and oauth2 security

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bhami Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=1382)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=1382) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by jgrandja** [comment]
@bhami Closing this PR as I believe this was a mistake?

**Comment by pivotal-issuemaster** [comment]
@bhami Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=1382)!

**Comment by pivotal-issuemaster** [comment]
@bhami Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=1382)!

**Pull request closed without merging**
