### PR TITLE
change modifer from 'private' to 'protected'

### PR DESCRIPTION
**Pull request by chinatsui**
@dsyer 
Hi, I have a request to apply this change as the involved 3 methods have potential requirement to be overridden in a custom situation.

### CODE REVIEW

**Comment by TradeshiftCyh** [comment]
@dsyer

**Comment by pivotal-issuemaster** [comment]
@TradeshiftCyh Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=843) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by dsyer** [comment]
I'm not keen on opening up methods without some justification ("I want it" doesn't really count). In this case I'm even more nervous because I suspect that if you override one of those and not the others you will break everything.

**Comment by jgrandja** [comment]
@chinatsui I agree with @dsyer. There has to be a good reason(s) for opening up `private` API.

**Pull request closed without merging**
