### PR TITLE
Little update to TokenEndpoint.java to use right parameters annotation for RequestMethod.POST

### PR DESCRIPTION
**Pull request by leandrobarcellos**
Obvious Fix: Change the parameter annotation at line 87 from @RequestParam to @RequestBody. It's more standardized.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@leandrobarcellos Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=1276)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=1276) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@leandrobarcellos This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by leandrobarcellos** [comment]
Ok. Now, what should I do remove the continuous integration error? Checking my modification I realize that I wasn't importing the *import org.springframework.web.bind.annotation.RequestBody* class.
Then I correct that on another commit... 
Thanks.

**Comment by jgrandja** [comment]
@leandrobarcellos Thank you for the PR.

Although, it makes sense to use `@RequestBody` over `@RequestParam` in the `TokenEndpoint`, it doesn't mean `@RequestParam` is incorrect in this case either. The `TokenEndpoint` expects request params and the current `@RequestParam Map<String, String> parameters` is simply converting **each** request parameter into the `Map`.

Furthermore, there are a few failing tests as a result of this change and I'm not confident that this should be applied given that the `TokenEndpoint` is a major touchpoint in the framework.

Given this, I'm going to close this PR as the current implementation works as expected.

**Pull request closed without merging**
