### PR TITLE
Synchronized double-checked on Jwk definitions

### PR DESCRIPTION
**Pull request by leomillon**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@leomillon Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=1443)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=1443) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@leomillon Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=1443)!

**Comment by leomillon** [comment]
#1405

**Comment by clemstoquart** [comment]
Hi Spring security team,

This is a pretty important fix. Can someone review it ?

Thanks

**Comment by jgrandja** [comment]
Thanks for the PR @leomillon. This is now in master via 852cec2

**Pull request closed without merging**
