### PR TITLE
Handle the presence of x5c x5t in JWK

### LINKED ISSUE #1082: JwkSetConverter should handle arrays e.g x5c
We're trying to use Auth0, but JwkSetConverter is only set up to handle strings, yet x5c is an array (as specified at https://tools.ietf.org/html/rfc7515#section-4.1.6), so the parsing blows up.

Is the workaround as simple as fix as it may appear (skip the x5 fields)?

### PR DESCRIPTION
**Pull request by nealeu**
This is sufficient to resolve #1082

### CODE REVIEW

**Comment by jgrandja** [comment]
Thanks for the PR @nealeu. I added some polish and merged to master.

**Comment by nealeu** [comment]
Thanks for doing so promptly after the obvious Spring 5-related work.  It's good timing as I got my Auth0 with JWK stuff working today with a bit too much copy-paste of closed classes.  I'm hoping you'll be able to make life a bit easier for us on that front, as it's really important for us with the automatic key rotation.

**Comment by jgrandja** [comment]
@nealeu As an FYI, we're not planning on opening up the JWK-related classes as we're not looking to build too much more support than what is already provided. Our intention is to bring the JWK feature to Spring Security 5 and build full support there instead. As of now, our focus is on the client side and next will be the Resource Server side which will entail the JWK feature.

**Comment by nealeu** [comment]
Thanks for the FYI.  We can get by with a bit of copy paste for what's closed.  Good to hear focus on future release with all the reactive goodies it brings :)

**Pull request closed without merging**
