### PR TITLE
Fix issue#1245: parseSSHPublicKey

### PR DESCRIPTION
**Pull request by shilei812**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@shilei812 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=1246)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=1246) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@shilei812 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=1246)!

**Comment by jgrandja** [comment]
Thanks for the PR @shilei812. Can you please add a test demonstrating the issue.

**Comment by jgrandja** [comment]
Closing due to lack of requested feedback.

**Pull request closed without merging**
