### PR TITLE
Fixes resetting the original auth object after chain.

### PR DESCRIPTION
**Pull request by rpvilao**
http://stackoverflow.com/questions/35345655/securitycontext-is-not-cleared-after-calling-the-chain-on-oauth2authenticationpr

### CODE REVIEW

**Comment by jgrandja** [comment]
Hi @rpvilao. I've looked at your PR and your posting on SO and don't feel this is a bug. Are you able to provide me a sample that reproduces this issue that you are having? I'm going to close this for now but will re-open and investigate further if you can provide me a sample.

**Comment by rpvilao-gymondo** [comment]
Hi,

The idea is the following: you'll need two endpoints one that requires auth and another that is public. You make the request to the secured one first and to the second after. The second request will have the authentication principal context of the first.

**Comment by jgrandja** [comment]
@rpvilao-gymondo If the Bearer token is passed on the 2nd request in the Authorization header (just like the 1st request) then yes the `Authentication` will be the same on the 2nd request, as expected. Even though the 2nd request is a public endpoint with `permitAll` configured, the `OAuth2AuthenticationProcessingFilter` will still extract the `Authentication` from the incoming Bearer token...it just won't be used to enforce authorization given the 2nd request is configured with `permitAll`.

**Comment by rpvilao-gymondo** [comment]
I know but it's happening without passing the token. It just takes the one from before because it's not cleared from the thread context.

**Comment by jgrandja** [comment]
@rpvilao-gymondo I changed my test to not pass the Bearer Token on the 2nd request and the Authentication is **not loaded** from the 1st request. The `SecurityContext` is cleared after the 1st request completes as expected. As already mentioned, please provide a sample of your scenario that I can look at and help solve your issue. I cannot reproduce the same scenario you have described. Thanks.

**Comment by rpvilao-gymondo** [comment]
Thanks for the effort you put into this. As soon as I have some spare time I'll get back to it. Thanks again!

**Comment by rpvilao-gymondo** [comment]
So for me it's really a pain in the ass to provide you with a package to reproduce even because I'm using a database for the token store and I have separate servers for resource and oauth. The way I'm configuring it is the following:

```
    @Override
    public void configure(HttpSecurity http) throws Exception {
        final ExpressionUrlAuthorizationConfigurer<HttpSecurity>.ExpressionInterceptUrlRegistry registry =
                http.addFilterAfter(authorisationFilter(), SwitchUserFilter.class).authorizeRequests();

        HttpUtil.SECURED_METHODS.forEach(x -> registry.regexMatchers(x, SECURED_PATTERN).access(format("hasAnyRole('%s', '%s')", UserRole.USER, UserRole.LIMITED_USER)));
    }
```

Basically SECURED_METHODS is a list of methods that I configure to be under the secured realm. The secured pattern is just a regex: /([^/].*?)/secured/.*

The authorisation filter is a simple filter that only checks if the user's subscription is valid and it's not used for the public calls.

Then I have:
```
    @RequestMapping
    public Page<ProgramV1Dto> list(
            @AuthenticationPrincipal OAuth2UserDetails oAuth2UserDetails) {
        System.out.println(oAuth2UserDetails);
     }
```
And it prints:
**Without a token**
null 
**With a token**
OAuth2UserDetails{id=1, authorities=[USER], password=[PROTECTED], username=ola@example.com, accountNonExpired=true, accountNonLocked=true, credentialsNonExpired=true, enabled=true, client=androidtv, accessToken=null}
**Without the token again**
OAuth2UserDetails{id=1, authorities=[USER], password=[PROTECTED], username=ola@example.com, accountNonExpired=true, accountNonLocked=true, credentialsNonExpired=true, enabled=true, client=androidtv, accessToken=null}

**Comment by jgrandja** [comment]
I really do need a sample in order to be effective in troubleshooting your issue. All I need is the Resource Server sample. For your `TokenStore`, you can configure an `InMemoryTokenStore` and set it on your `ResourceServerSecurityConfigurer`. Just make sure you save the `OAuth2AccessToken` into the `TokeStore` before you run your test.

**Comment by rpvilao-gymondo** [comment]
Hi,

So I was isolating the code for you and I was testing and decided to write some scripts using curl and I realised that with curl I cannot reproduce it... only with postman via the browser. Meaning that the fact the browser is sending cookies (JSESSIONID probably) enable this to happen. Is there a way to prevent this?

**Comment by jgrandja** [comment]
@rpvilao-gymondo No worries. I'm glad you got it working now.

**Pull request closed without merging**
