### PR TITLE
provide an extension point for people who want to alter the serializa…

### PR DESCRIPTION
**Pull request by benkiefer**
…tion of the authorization code's authentication object (ex: encrypt/decrypt it)

### CODE REVIEW

**Comment by benkiefer** [comment]
This is the same functionality that is provided with the JdbcTokenStore

**Comment by benkiefer** [comment]
Any movement on this?

**Comment by antechrestos** [comment]
Facing the same trouble here. This may be a great thing.
Could be implemented using a `@Service` annotated class with one by default doing the current logic?

**Comment by pivotal-issuemaster** [comment]
@benkiefer Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=617) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@benkiefer Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=617)!

**Comment by jgrandja** [comment]
@benkiefer I'm going to close this PR as it's quite old. If this is still valid, can you please rebase off master and resubmit a new PR.

**Pull request closed without merging**
