### PR TITLE
Feature/support non oauth2 response types refactored

### PR DESCRIPTION
**Pull request by oharsta**
New pull request based on the https://github.com/spring-projects/spring-security-oauth/issues/626 with the suggestions from dsyer implemented.

### CODE REVIEW

**Comment by oharsta** [comment]
Travis fails with:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------


The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).

The build has been terminated.
```

**Comment by pivotal-issuemaster** [comment]
@oharsta Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=657) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by oharsta** [comment]
@pivotal-issuemaster , I already signed the Contributor License Agreement some time ago. See https://github.com/spring-projects/spring-security-oauth/pull/50. My confirmation number is 33620120911014936.

**Comment by pivotal-issuemaster** [comment]
@oharsta Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security-oauth&pullRequestId=657)!

**Comment by jgrandja** [comment]
Closing as this is a major change that we are no longer accepting.

As you may be aware, this project is in maintenance mode and will reach EOL in the very near future. Please see the [initial announcement](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security) and [follow-up announcement](https://spring.io/blog/2019/11/14/spring-security-oauth-2-0-roadmap-update) for further details.

At this time, we are only accepting bug fixes and minor enhancements that can be cleanly merged into master.

Thank you for your understanding and we would welcome your contributions to the new OAuth 2.0 / OpenID Connect support in [Spring Security](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2).

**Pull request closed without merging**
