### PR TITLE
Prevent user from obtaining token via client_credentials or password grant

### PR DESCRIPTION
**Pull request by jgrandja**
Fixes gh-808

### CODE REVIEW

**Comment by dsyer** [comment]
LGTM

**Comment by rwinch** [comment]
Can we add a test for the XML use case?

**Comment by rwinch** [comment]
We should also provide a link to a sample that demonstrates the app broken and then fixed for both Java Config and XML config. The link should be posted on the issue and then also posted on our blog post with the release. The primary reason for this is for the XML configuration we cannot just say update to the latest. We need to ensure users know how to configure it correctly.

**Comment by jgrandja** [comment]
XML tests have been added for valid and invalid configuration.

**Comment by jgrandja** [comment]
@rwinch Are you ok if we provide a link to the Java Config and Xml Config Tests in the blog post and Issue instead of the sample repo you requested? The tests demonstrate a valid and invalid Xml Config and as far as the Java Config goes all the user needs to do is update to 2.0.11.RELEASE.
@dsyer and I spoke and we feel this is sufficient. What do you think?

**Comment by rwinch** [comment]
That seems ok to me

**Pull request merged**
